version: '3.9'

services:
  postgres:
    image: postgres:16

    container_name: selfkind-postgres

    restart: always

    environment:
      POSTGRES_USER: selfkind
      POSTGRES_PASSWORD: selfkind_password
      POSTGRES_DB: selfkind

    ports:
      - '5435:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: selfkind-redis

    restart: always

    ports:
      - '6382:6379'

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: